const $=s=>document.querySelector(s);
const state={data:null,week:null,day:null,dayName:"",session:null,timer:null,lastTick:0,gpsWatch:null,audio:null,cadenceTimer:null,lastWarningSecond:null,deferredInstall:null,wakeLock:null,musicAudio:null,mediaPrimer:null,musicLibrary:[],musicDirectoryHandle:null,musicIndexedAt:null,phaseTrackAssignments:new Map(),musicPositions:new Map(),phaseTrackQueues:new Map(),musicUsedByPhase:new Map(),currentMusicKey:null,musicCurrentPhase:null,musicCurrentTrack:null,musicPendingResume:0,musicRetryTimer:null,musicWatchdog:null,musicStartedAt:0,speechToken:0,speechUtterance:null,speechWatchdog:null,musicTapTimer:null,lastMusicTap:0,musicRestorePromise:null,gpsMonitor:null,trainingViewMode:0,swipeStartX:0,swipeStartY:0,startingTraining:false};
const zoneColor=z=>({Z1:"#72a7d8",Z2:"#58c472",Z3:"#e0c23b",Z4:"#ff9b45",Z5:"#ef6262"})[(z||"").match(/Z[1-5]/)?.[0]]||"#718096";
const zoneHrPct={Z1:[50,60],Z2:[60,70],Z3:[70,80],Z4:[80,90],Z5:[90,100]};
const defaults={maxHr:185,gps:true,warningEnabled:true,voiceEnabled:true,cadenceEnabled:true,musicEnabled:true,warningVolume:.8,voiceVolume:.9,cadenceVolume:.45,musicVolume:.35,cadenceOverride:""};
const getSetting=(k)=>{const v=localStorage.getItem(`rpc.${k}`);if(v===null)return defaults[k];if(typeof defaults[k]==="boolean")return v==="true";if(typeof defaults[k]==="number")return Number(v);return v};

async function init(){
  const res=await fetch("./data/entrenamiento.json");
  if(!res.ok)throw new Error(`No se pudo cargar el plan (${res.status})`);
  state.data=await res.json();
  if(!Array.isArray(state.data?.weeks)||!state.data.weeks.length)throw new Error("El archivo del plan no contiene semanas válidas");
  const savedWeek=Number(localStorage.getItem("rpc.week"))||1,savedDay=localStorage.getItem("rpc.day")||"Martes";
  $("#weekSelect").innerHTML=state.data.weeks.map(w=>`<option value="${w.number}">${w.number}${w.recovery?" · Descarga":""}</option>`).join("");
  $("#weekSelect").value=state.data.weeks.some(w=>w.number===savedWeek)?savedWeek:1;loadDays(savedDay);
  $("#weekSelect").addEventListener("change",()=>loadDays("Martes"));$("#daySelect").addEventListener("change",render);
  $("#prepareButton").addEventListener("click",openPrepare);$("#backButton").addEventListener("click",closePrepare);$("#prepareConfigButton").addEventListener("click",openConfig);$("#startButton").addEventListener("click",startTraining);
  $("#addPhaseButton").addEventListener("click",()=>openPhaseEditor());$("#resetPhasesButton").addEventListener("click",resetCustomPhases);$("#phaseList").addEventListener("click",handlePhaseAction);$("#savePhaseButton").addEventListener("click",savePhase);
  $("#stageClockButton").addEventListener("click",toggleStageClock);$("#currentStageCard").addEventListener("click",replayCurrentPhaseVoice);$("#pauseButton").addEventListener("click",togglePause);$("#finishButton").addEventListener("click",()=>$("#finishDialog").showModal());$("#confirmFinish").addEventListener("click",finishTraining);$("#previousPhaseButton").addEventListener("click",()=>changePhaseManually(-1));$("#nextPhaseButton").addEventListener("click",()=>changePhaseManually(1));setupTrainingSwipe();setupPullToRefreshGuard();
  $("#configButton").addEventListener("click",openConfig);$("#saveConfigButton").addEventListener("click",saveConfig);$("#resetCadenceAuto").addEventListener("click",resetCadenceOverride);$("#cadenceOverride").addEventListener("input",updateCadenceAutoButton);
  ["warningVolume","voiceVolume","cadenceVolume","musicVolume"].forEach(id=>$("#"+id).addEventListener("input",updateVolumeOutputs));
  $("#musicFiles").addEventListener("change",loadMusicLibrary);$("#chooseMusicFolder")?.addEventListener("click",chooseMusicFolder);$("#reindexMusicFolder")?.addEventListener("click",()=>restoreMusicFolder(true));$("#phaseMusicButton").addEventListener("click",handlePhaseMusicTap);$("#progressCard").addEventListener("click",openHistory);$("#saveFinish").addEventListener("click",saveAndFinish);$("#editPhaseMusic").addEventListener("change",togglePreferredMusicFields);
  if((localStorage.getItem("rpc.view")||"home")==="prepare")openPrepare(false);
  renderProgressCard();
  state.musicRestorePromise=restoreMusicFolder(false).catch(()=>{updateMusicLibraryStatus();return false});
  setupInstallPrompt();
  if("serviceWorker" in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});
}
function currentWeek(){return state.data.weeks.find(w=>w.number===Number($("#weekSelect").value))}
function loadDays(preferred){const w=currentWeek(),names=Object.keys(w.days);$("#daySelect").innerHTML=names.map(d=>`<option>${d}</option>`).join("");$("#daySelect").value=names.includes(preferred)?preferred:names[0];render()}
function render(){const w=currentWeek(),day=$("#daySelect").value,d=w.days[day];state.week=w;state.day=d;state.dayName=day;localStorage.setItem("rpc.week",w.number);localStorage.setItem("rpc.day",day);$("#weekTitle").textContent=`Semana ${w.number} · ${w.title}`;$("#phaseName").textContent=w.phase;$("#phaseObjective").textContent=w.phaseObjective;$("#duration").textContent=d.duration||"—";$("#zone").textContent=d.zone||d.phases?.[0]?.zone||"—";$("#cadence").textContent=d.cadence||d.phases?.[0]?.cadence||"Cadencia libre";$("#type").textContent=d.type||"MTB";$("#distance").textContent=d.distance?`Distancia estimada: ${d.distance}`:"";$("#nutrition").textContent=d.nutrition;$("#technique").textContent=d.technique}
const customKey=()=>`rpc.phases.${state.week.number}.${state.dayName}`;
function originalPhases(){return state.day.phases?.length?structuredClone(state.day.phases):[{name:"Sesión continua",duration:state.day.duration,zone:state.day.zone,cadence:state.day.cadence,technique:state.day.technique}]}
function getPhases(){try{return JSON.parse(localStorage.getItem(customKey()))||originalPhases()}catch{return originalPhases()}}
function saveCustomPhases(phases){localStorage.setItem(customKey(),JSON.stringify(phases))}
function openPrepare(pushHistory=true){$("#prepareTitle").textContent=state.day.title;$("#prepareWeek").textContent=`Semana ${state.week.number} · ${state.dayName}`;renderPhaseList();showView("prepare");if(pushHistory&&!location.hash)history.pushState({prepare:true},"","#preparar")}
function renderPhaseList(){const phases=getPhases();$("#prepareDuration").textContent=formatClock(phases.reduce((a,p)=>a+parseDurationSeconds(p.duration),0),true);$("#phaseList").innerHTML=phases.map((p,i)=>`<article class="phase-row" style="--zone:${zoneColor(p.zone||p.name)}"><span class="phase-index">${i+1}</span><div><h3>${escapeHtml(p.name)}</h3><p>${escapeHtml(p.zone||"Sin zona")} · ${escapeHtml(p.cadence||state.day.cadence||"Cadencia libre")}</p></div><span class="phase-time">${escapeHtml(p.duration||"—")}</span><div class="phase-detail">${escapeHtml(p.technique||"Sin técnica específica")} · Pulsaciones: ${escapeHtml(p.hr||"según zona")}</div><div class="phase-actions"><button data-action="edit" data-index="${i}">Editar</button><button data-action="up" data-index="${i}">↑</button><button data-action="down" data-index="${i}">↓</button><button class="delete-phase" data-action="delete" data-index="${i}">Eliminar</button></div></article>`).join("")}
function handlePhaseAction(e){const b=e.target.closest("button[data-action]");if(!b)return;const phases=getPhases(),i=Number(b.dataset.index),a=b.dataset.action;if(a==="edit")return openPhaseEditor(i);if(a==="delete")phases.splice(i,1);if(a==="up"&&i>0)[phases[i-1],phases[i]]=[phases[i],phases[i-1]];if(a==="down"&&i<phases.length-1)[phases[i+1],phases[i]]=[phases[i],phases[i+1]];if(!phases.length)phases.push({name:"Nuevo período",duration:"5 min",zone:"Z1"});saveCustomPhases(phases);renderPhaseList()}
function openPhaseEditor(i=""){const p=i===""?{name:"Nuevo período",duration:"5 min",technique:"",zone:"Z1",cadence:state.day.cadence||"",hr:"",music:"auto",musicPreferences:[]}:getPhases()[i];$("#editPhaseIndex").value=i;for(const [id,key] of [["editPhaseName","name"],["editPhaseDuration","duration"],["editPhaseTechnique","technique"],["editPhaseZone","zone"],["editPhaseCadence","cadence"],["editPhaseHr","hr"]])$("#"+id).value=p[key]||"";populatePhaseMusicSelect(p.music||"auto",p.musicPreferences||[]);togglePreferredMusicFields();$("#phaseEditorDialog").showModal()}
function savePhase(e){e.preventDefault();const phases=getPhases(),i=$("#editPhaseIndex").value,p={name:$("#editPhaseName").value.trim(),duration:$("#editPhaseDuration").value.trim(),technique:$("#editPhaseTechnique").value.trim(),zone:$("#editPhaseZone").value.trim(),cadence:$("#editPhaseCadence").value.trim(),hr:$("#editPhaseHr").value.trim(),music:$("#editPhaseMusic").value,musicPreferences:[1,2,3].map(n=>$("#editPhaseMusic"+n).value).filter(Boolean)};if(!p.name||!p.duration)return;if(i==="")phases.push(p);else phases[Number(i)]=p;saveCustomPhases(phases);$("#phaseEditorDialog").close();renderPhaseList()}
function resetCustomPhases(){localStorage.removeItem(customKey());renderPhaseList()}
function closePrepare(){showView("home");if(location.hash)history.replaceState(null,"",location.pathname)}
function showView(name){$("#homeView").hidden=name!=="home";$("#prepareView").hidden=name!=="prepare";$("#trainingView").hidden=name!=="training";localStorage.setItem("rpc.view",name);scrollTo(0,0)}
function parseDurationSeconds(text){if(!text)return 0;const n=String(text).toLowerCase().replace(/,/g,'.'),h=Number(n.match(/(\d+(?:\.\d+)?)\s*h/)?.[1]||0),m=Number(n.match(/(\d+(?:\.\d+)?)\s*min/)?.[1]||0),s=Number(n.match(/(\d+(?:\.\d+)?)\s*s(?:eg)?/)?.[1]||0);let t=h*3600+m*60+s;if(!t)t=Number(n.match(/\d+(?:\.\d+)?/)?.[0]||0)*60;return Math.max(1,Math.round(t))}
function repetitionInfo(phase){const duration=String(phase?.duration||""),name=String(phase?.name||"");let m=duration.match(/(\d+)\s*[×xX]\s*(\d+(?:[.,]\d+)?)\s*(min|s(?:eg)?)/i);if(m)return {count:Number(m[1]),unit:`${m[2]} ${m[3]}`};const count=name.match(/(?:^|\D)(\d+)\s*[×xX]\s*(?:\d+(?:[.,]\d+)?)?(?:\D|$)/i)?.[1];const unit=duration.match(/(\d+(?:[.,]\d+)?)\s*(min|s(?:eg)?)/i);return count&&unit?{count:Number(count),unit:`${unit[1]} ${unit[2]}`} : null}
function expandPhases(source){const out=[];for(let i=0;i<source.length;i++){const p={...source[i]},rep=repetitionInfo(p),next=source[i+1],isRecovery=next&&/recuperaci[oó]n/i.test(next.name||"");if(!rep||rep.count<2){out.push(p);continue}const blockId=`${state.week?.number||0}-${state.dayName}-${i}`;for(let r=1;r<=rep.count;r++){out.push({...p,duration:rep.unit,repetition:r,repetitionCount:rep.count,name:`${cleanPhaseName(p.name)} · ${r}/${rep.count}`,musicGroup:`${blockId}-work`,musicResume:true});if(isRecovery&&r<rep.count)out.push({...next,name:cleanPhaseName(next.name),intercalatedRecovery:true,musicGroup:`${blockId}-recovery`,musicResume:true})}if(isRecovery)i++}return out}
function buildSession(){state.phaseTrackAssignments.clear();state.musicPositions.clear();state.phaseTrackQueues.clear();state.musicUsedByPhase.clear();state.currentMusicKey=null;state.musicCurrentPhase=null;state.musicCurrentTrack=null;const phases=expandPhases(getPhases()).map((p,i)=>({...p,index:i,durationSeconds:parseDurationSeconds(p.duration)})),plannedTotal=phases.reduce((s,p)=>s+p.durationSeconds,0);return {phases,phaseIndex:0,phaseElapsed:0,totalElapsed:0,averageElapsed:0,plannedTotal,paused:false,showRemaining:false,maxHr:getSetting("maxHr"),gps:getSetting("gps"),warningEnabled:getSetting("warningEnabled"),voiceEnabled:getSetting("voiceEnabled"),cadenceEnabled:getSetting("cadenceEnabled"),musicEnabled:getSetting("musicEnabled"),warningVolume:getSetting("warningVolume"),voiceVolume:getSetting("voiceVolume"),cadenceVolume:getSetting("cadenceVolume"),musicVolume:getSetting("musicVolume"),cadenceOverride:getSetting("cadenceOverride"),musicPausedByUser:false,distance:0,elevation:0,elevationAnchor:null,altitudeWindow:[],speed:0,hr:0,speedWeighted:0,hrWeighted:0,sampleSeconds:0,finished:false,transition:true,transitionRemaining:10,lastPosition:null,gpsAnchor:null,gpsMotionStreak:0,gpsMoving:false,gpsLastMotionAt:0,gpsSpeedUpdatedAt:0,lastGpsReceived:0,gpsResumePending:false,gpsHiddenAt:0,phaseResults:phases.map(()=>({status:"pending",elapsed:0})),completedPhaseSeconds:0}}
async function startTraining(){if(state.startingTraining)return;const button=$("#startButton"),originalLabel=button?.textContent||"INICIAR ENTRENAMIENTO";state.startingTraining=true;if(button){button.disabled=true;button.textContent="PREPARANDO…"}const audioUnlock=unlockAudio();try{if(getSetting("musicEnabled")&&!state.musicLibrary.length){if(state.musicRestorePromise){if(button)button.textContent="CARGANDO MÚSICA…";try{await state.musicRestorePromise}catch{}state.musicRestorePromise=null}if(!state.musicLibrary.length){const handle=state.musicDirectoryHandle;if(handle?.requestPermission){if(button)button.textContent="AUTORIZANDO MÚSICA…";let permission="prompt";try{permission=await handle.requestPermission({mode:"read"})}catch{}if(permission==="granted"){if(button)button.textContent="CARGANDO MÚSICA…";await indexMusicDirectory(handle,false)}else await ensureMusicLibraryReady(false)}else{if(button)button.textContent="CARGANDO MÚSICA…";await ensureMusicLibraryReady(true)}}}await audioUnlock;if(button)button.textContent="INICIANDO…";state.session=buildSession();state.trainingViewMode=0;setTrainingView(0);renderTrainingStatic();showView("training");history.replaceState({training:true},"","#entrenamiento");if(state.session.gps)startGps(false);beginTransition();await requestWakeLock();state.lastTick=performance.now();clearInterval(state.timer);state.timer=setInterval(tick,200)}finally{state.startingTraining=false;if(button){button.disabled=false;button.textContent=originalLabel}}}
function renderTrainingStatic(){const s=state.session;$("#liveWeekDay").textContent=`SEMANA ${state.week.number} · ${state.dayName.toUpperCase()}`;updatePhaseTargets(s.phases[s.phaseIndex])}
function updatePhaseTargets(p){const s=state.session,zone=p.zone||state.day.zone||"—",cad=p.cadence||"Cadencia libre",cadDisplay=/^cadencia libre$/i.test(String(cad).trim())?"Libre":cad;document.documentElement.style.setProperty("--zone-color",zoneColor(zone));$("#targetTime").textContent=compactDuration(p.duration,p.durationSeconds);$("#targetZone").textContent=zone;$("#targetCadence").textContent=cadDisplay;$("#targetHr").textContent=p.hr&&p.hr!=="Según zona"?p.hr:hrTarget(zone,s.maxHr);$("#currentPhaseName").textContent=cleanPhaseName(p.name);$("#livePhaseCounter").textContent=`ETAPA ${p.index+1}/${s.phases.length}`;stopCadencePulse();if(!s.paused&&!s.transition)startCadencePulse();switchPhaseMusic(p)}
function hrTarget(zone,maxHr){const z=(zone||"").match(/Z[1-5]/)?.[0];if(!z)return "—";const[a,b]=zoneHrPct[z];return `${Math.round(maxHr*a/100)}–${Math.round(maxHr*b/100)}`}
function compactDuration(raw,seconds){if(seconds<60)return `${seconds} s`;if(seconds<3600)return seconds%60?formatClock(seconds,false):`${seconds/60} min`;return raw||formatClock(seconds,false)}
function averageSessionSpeed(s){return s?.averageElapsed>0?s.distance*3600/s.averageElapsed:0}
function accumulateSessionMetrics(seconds){const s=state.session;if(!s?.lastPosition||seconds<=0)return;const gpsFresh=Date.now()-s.lastGpsReceived<15000;if(!gpsFresh)return;s.speedWeighted+=s.speed*seconds;s.hrWeighted+=s.hr*seconds;s.sampleSeconds+=seconds}
function tick(){const now=performance.now(),elapsed=Math.max(0,Math.min((now-state.lastTick)/1000,21600));state.lastTick=now;const s=state.session;if(!s||s.paused||s.finished)return;let pending=elapsed;while(pending>0&&state.session===s&&!s.paused&&!s.finished){if(s.transition){const step=Math.min(pending,Math.max(0,s.transitionRemaining));s.transitionRemaining-=step;s.averageElapsed+=step;pending-=step;if(s.transitionRemaining<=.001)startActivePhase();if(step<=0&&s.transition)break;continue}const p=s.phases[s.phaseIndex],available=Math.max(0,p.durationSeconds-s.phaseElapsed),step=Math.min(pending,available);s.phaseElapsed+=step;s.totalElapsed+=step;s.averageElapsed+=step;accumulateSessionMetrics(step);pending-=step;handleWarningBeep(p.durationSeconds-s.phaseElapsed);if(s.phaseElapsed>=p.durationSeconds-.001)advancePhase();else if(step<=0)break}updateTrainingUI()}
function beginTransition(){const s=state.session;s.transition=true;s.transitionRemaining=10;s.phaseElapsed=0;state.lastWarningSecond=null;$("#trainingView").classList.add("is-transition");stopCadencePulse();const p=s.phases[s.phaseIndex];speakPhase(p);updateTrainingUI()}
function startActivePhase(){const s=state.session;s.transition=false;s.phaseElapsed=0;$("#trainingView").classList.remove("is-transition");beep(900,.16,s.warningVolume);startCadencePulse()}
function completeCurrentPhase(){const s=state.session;if(!s)return;const p=s.phases[s.phaseIndex],r=s.phaseResults[s.phaseIndex];if(r&&r.status!=="completed"){r.status="completed";r.elapsed=p.durationSeconds;s.completedPhaseSeconds+=p.durationSeconds}}
function advancePhase(){const s=state.session;completeCurrentPhase();if(s.phaseIndex>=s.phases.length-1){s.paused=true;s.finished=true;stopCadencePulse();stopGps();$("#pauseButton").textContent="Completado";$("#pauseButton").disabled=true;updateTrainingUI();return}s.phaseIndex++;updatePhaseTargets(s.phases[s.phaseIndex]);beginTransition();if(navigator.vibrate)navigator.vibrate([180,100,180])}
function changePhaseManually(delta){const s=state.session;if(!s||s.finished)return;const next=s.phaseIndex+delta;if(next<0||next>=s.phases.length)return;const currentResult=s.phaseResults[s.phaseIndex];if(currentResult&&currentResult.status!=="completed"){currentResult.status="skipped";currentResult.elapsed=Math.min(s.phaseElapsed,s.phases[s.phaseIndex].durationSeconds)}stopCadencePulse();saveCurrentMusicPosition();s.phaseIndex=next;s.phaseElapsed=0;s.transition=false;s.transitionRemaining=0;updatePhaseTargets(s.phases[s.phaseIndex]);beginTransition();updateTrainingUI();if(navigator.vibrate)navigator.vibrate(80)}
function cleanDrivingDuration(p){const sec=p?.durationSeconds||parseDurationSeconds(p?.duration||"");return sec%60===0?`${Math.round(sec/60)} min`:formatClock(sec,false)}
function drivingCadence(p){const c=p?.cadence||"Cadencia libre";return /^cadencia libre$/i.test(String(c).trim())?"Libre":String(c).replace(/\s*rpm/i," rpm")}
function updateDrivingView(){const s=state.session;if(!s)return;const p=s.phases[s.phaseIndex],has=Boolean(s.lastPosition),avg=averageSessionSpeed(s),progress=s.transition?(10-s.transitionRemaining)*10:Math.min(100,s.phaseElapsed/p.durationSeconds*100);$("#drivingPhaseName").textContent=cleanPhaseName(p.name);$("#drivingPhaseMeta").textContent=`${cleanDrivingDuration(p)} · ${drivingCadence(p)}`;$("#drivingSpeed").textContent=has?s.speed.toFixed(1):"—";$("#drivingDistance").textContent=has?s.distance.toFixed(2):"—";$("#drivingAverage").textContent=s.sampleSeconds?avg.toFixed(1):"—";$("#drivingProgress").style.width=`${Math.max(0,progress)}%`;$("#previousPhaseButton").disabled=s.phaseIndex===0;$("#nextPhaseButton").disabled=s.phaseIndex===s.phases.length-1}
function setTrainingView(mode){state.trainingViewMode=mode?1:0;const d=$("#drivingView"),dots=[...document.querySelectorAll("#trainingPager i")];if(d)d.hidden=state.trainingViewMode===0;dots.forEach((dot,i)=>dot.classList.toggle("active",i===state.trainingViewMode));updateDrivingView()}

function findTouchScrollContainer(node){
  for(let element=node instanceof Element?node:node?.parentElement;
      element&&element!==document.body;
      element=element.parentElement){
    const style=getComputedStyle(element);
    if(/auto|scroll|overlay/.test(style.overflowY)
       &&element.scrollHeight>element.clientHeight+1)return element
  }
  return document.scrollingElement||document.documentElement
}
function setupPullToRefreshGuard(){
  let startX=0,startY=0,scrollContainer=null;
  const reset=()=>{scrollContainer=null};
  document.addEventListener("touchstart",event=>{
    if(event.touches.length!==1)return;
    const touch=event.touches[0];
    startX=touch.clientX;
    startY=touch.clientY;
    scrollContainer=findTouchScrollContainer(event.target)
  },{passive:true,capture:true});
  document.addEventListener("touchmove",event=>{
    if(event.touches.length!==1||!event.cancelable)return;
    const touch=event.touches[0],
      dx=touch.clientX-startX,
      dy=touch.clientY-startY;
    if(dy<=0||Math.abs(dy)<=Math.abs(dx))return;
    const container=scrollContainer||document.scrollingElement||document.documentElement;
    const isDocument=container===document.scrollingElement
      ||container===document.documentElement
      ||container===document.body;
    const atTop=isDocument
      ?Math.max(window.scrollY||0,document.documentElement.scrollTop||0,document.body.scrollTop||0)<=0
      :container.scrollTop<=0;
    if(atTop)event.preventDefault()
  },{passive:false,capture:true});
  document.addEventListener("touchend",reset,{passive:true,capture:true});
  document.addEventListener("touchcancel",reset,{passive:true,capture:true})
}

function setupTrainingSwipe(){const el=$("#trainingView");el.addEventListener("touchstart",e=>{const t=e.changedTouches[0];state.swipeStartX=t.clientX;state.swipeStartY=t.clientY},{passive:true});el.addEventListener("touchend",e=>{const t=e.changedTouches[0],dx=t.clientX-state.swipeStartX,dy=t.clientY-state.swipeStartY;if(Math.abs(dx)>55&&Math.abs(dx)>Math.abs(dy)*1.35)setTrainingView(dx<0?1:0)},{passive:true})}
function updateTrainingUI(){const s=state.session;if(!s)return;const p=s.phases[s.phaseIndex],remaining=Math.max(0,p.durationSeconds-s.phaseElapsed);$("#stageCaption").textContent="ETAPA";$("#stageClock").textContent=s.transition?formatClock(s.transitionRemaining,false):formatClock(s.showRemaining?remaining:s.phaseElapsed,false);$("#stageClockLabel").textContent=s.transition?"PREPARACIÓN":s.showRemaining?"TIEMPO RESTANTE":"TIEMPO DE ETAPA";$("#stageClockButton").classList.toggle("show-remaining",!s.transition&&s.showRemaining);$("#totalClock").textContent=formatClock(s.totalElapsed,true);$("#stageProgress").style.width=s.transition?`${(10-s.transitionRemaining)*10}%`:`${Math.min(100,s.phaseElapsed/p.durationSeconds*100)}%`;$("#totalProgress").style.width=`${Math.min(100,s.totalElapsed/s.plannedTotal*100)}%`;const has=Boolean(s.lastPosition);$("#speedNow").textContent=has?s.speed.toFixed(1):"—";$("#hrNow").textContent=s.hr?s.hr:"—";$("#speedAvg").textContent=s.averageElapsed?averageSessionSpeed(s).toFixed(1):"—";$("#distanceTotal").textContent=has?s.distance.toFixed(2):"—";$("#elevationTotal").textContent=has?`+${Math.round(s.elevation)}`:"—";$("#hrAvg").textContent=s.sampleSeconds&&s.hrWeighted?Math.round(s.hrWeighted/s.sampleSeconds):"—";updateDrivingView()}
function formatClock(seconds,withHours){const t=Math.max(0,Math.floor(seconds)),h=Math.floor(t/3600),m=Math.floor(t%3600/60),s=t%60;return withHours?`${pad(h)}:${pad(m)}:${pad(s)}`:`${pad(Math.floor(t/60))}:${pad(s)}`}
const pad=n=>String(n).padStart(2,"0");
function toggleStageClock(){if(!state.session)return;state.session.showRemaining=!state.session.showRemaining;updateTrainingUI()}
function togglePause(){const s=state.session;if(!s||s.finished)return;s.paused=!s.paused;$("#pauseButton").textContent=s.paused?"Continuar":"Pausa";$("#pauseButton").classList.toggle("is-paused",s.paused);s.speed=0;s.gpsMotionStreak=0;s.gpsMoving=false;s.gpsLastMotionAt=0;s.gpsSpeedUpdatedAt=0;if(s.paused)stopCadencePulse();else{s.gpsAnchor=null;s.lastPosition=null;s.gpsResumePending=false;if(!s.transition)startCadencePulse()}state.lastTick=performance.now();updateTrainingUI()}
function openConfig(){for(const k of ["maxHr","cadenceOverride"])$("#"+k).value=state.session?.[k]??getSetting(k);for(const k of ["gps","warningEnabled","voiceEnabled","cadenceEnabled","musicEnabled"])$("#"+({gps:"gpsEnabled",warningEnabled:"warningEnabled",voiceEnabled:"voiceEnabled",cadenceEnabled:"cadenceEnabled",musicEnabled:"musicEnabled"}[k])).checked=state.session?.[k]??getSetting(k);for(const k of ["warningVolume","voiceVolume","cadenceVolume","musicVolume"])$("#"+k).value=state.session?.[k]??getSetting(k);updateCadenceAutoButton();updateVolumeOutputs();updateMusicLibraryStatus();$("#configDialog").showModal()}
function updateCadenceAutoButton(){const input=$("#cadenceOverride"),button=$("#resetCadenceAuto");if(!input||!button)return;const automatic=!String(input.value||"").trim();button.classList.toggle("is-active",automatic);button.setAttribute("aria-pressed",String(automatic))}
function resetCadenceOverride(){const input=$("#cadenceOverride");if(!input)return;input.value="";input.blur();updateCadenceAutoButton()}
function updateVolumeOutputs(){for(const k of ["warningVolume","voiceVolume","cadenceVolume","musicVolume"])$("#"+k+"Out").textContent=`${Math.round(Number($("#"+k).value)*100)}%`}
function saveConfig(e){e.preventDefault();const values={maxHr:Number($("#maxHr").value)||185,gps:$("#gpsEnabled").checked,warningEnabled:$("#warningEnabled").checked,voiceEnabled:$("#voiceEnabled").checked,cadenceEnabled:$("#cadenceEnabled").checked,musicEnabled:$("#musicEnabled").checked,warningVolume:Number($("#warningVolume").value),voiceVolume:Number($("#voiceVolume").value),cadenceVolume:Number($("#cadenceVolume").value),musicVolume:Number($("#musicVolume").value),cadenceOverride:$("#cadenceOverride").value.trim()};for(const[k,v]of Object.entries(values))localStorage.setItem(`rpc.${k}`,String(v));if(state.session){const oldGps=state.session.gps;Object.assign(state.session,values);updatePhaseTargets(state.session.phases[state.session.phaseIndex]);if(!values.gps)stopGps();else if(oldGps!==values.gps)startGps();if(!values.cadenceEnabled)stopCadencePulse();else if(!state.session.paused&&!state.session.transition)startCadencePulse();if(!values.musicEnabled)stopPhaseMusic();else switchPhaseMusic(state.session.phases[state.session.phaseIndex]);updateTrainingUI()}$("#configDialog").close()}
function saveAndFinish(){saveTrainingRecord();finishTraining()}
function finishTraining(){clearInterval(state.timer);state.timer=null;stopCadencePulse();stopMusicWatchdog();stopPhaseMusic();stopGps();releaseWakeLock();stopSpeech();if(state.session)state.session.finished=true;state.session=null;setTrainingView(0);$("#pauseButton").disabled=false;$("#pauseButton").textContent="Pausa";$("#pauseButton").classList.remove("is-paused");showView("home");renderProgressCard();history.replaceState(null,"",location.pathname)}
async function unlockAudio(){return (async()=>{try{state.audio??=new (window.AudioContext||window.webkitAudioContext)();if(state.audio.state==="suspended")await state.audio.resume()}catch{}try{state.mediaPrimer??=new Audio("data:audio/wav;base64,UklGRkQDAABXQVZFZm10IBAAAAABAAEAQB8AAIA+AAACABAAZGF0YSADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==");state.mediaPrimer.volume=0;await state.mediaPrimer.play();state.mediaPrimer.pause();state.mediaPrimer.currentTime=0}catch{}try{ensureMusicPlayer()}catch{}})()}
function beep(freq,duration,volume,type="sine",delay=0){const s=state.session;if(!s||volume<=0||!state.audio)return;const o=state.audio.createOscillator(),g=state.audio.createGain(),start=state.audio.currentTime+Math.max(0,delay);o.type=type;o.frequency.setValueAtTime(freq,start);g.gain.setValueAtTime(Math.max(.0001,volume*.18),start);o.connect(g).connect(state.audio.destination);o.start(start);g.gain.exponentialRampToValueAtTime(.0001,start+duration);o.stop(start+duration)}
function playStageWarning(sec,volume){const cues={5:[390,.24],4:[470,.26],3:[560,.28],2:[650,.31],1:[760,.42]},cue=cues[sec];if(!cue)return;beep(cue[0],cue[1],volume,"triangle");if(sec===1)beep(520,.2,volume*.9,"triangle",.22)}
function handleWarningBeep(remaining){const s=state.session,sec=Math.ceil(remaining);if(!s?.warningEnabled)return;if(sec<=5&&sec>=1&&sec!==state.lastWarningSecond){state.lastWarningSecond=sec;playStageWarning(sec,s.warningVolume)}}
function cadenceRpm(){const s=state.session,p=s?.phases?.[s.phaseIndex];if(!p)return 0;const override=Number(s.cadenceOverride);if(override>0)return override;if(p.metronome===false)return 0;if(Number(p.cadenceRpm)>0)return Number(p.cadenceRpm);const nums=String(p.cadence||"").match(/\d{2,3}/g)?.map(Number)||[];return nums.length>1?Math.round((nums[0]+nums[1])/2):(nums[0]||0)}
function startCadencePulse(){stopCadencePulse();const s=state.session,rpm=cadenceRpm();if(!s?.cadenceEnabled||!rpm||s.cadenceVolume<=0)return;beep(1100,.055,s.cadenceVolume);state.cadenceTimer=setInterval(()=>beep(1100,.055,s.cadenceVolume),60000/rpm)}
function stopCadencePulse(){clearInterval(state.cadenceTimer);state.cadenceTimer=null}
function spokenNumber(value){const words=["cero","uno","dos","tres","cuatro","cinco","seis","siete","ocho","nueve","diez","once","doce","trece","catorce","quince","dieciséis","diecisiete","dieciocho","diecinueve","veinte"];const n=Number(value);return Number.isInteger(n)&&n>=0&&n<words.length?words[n]:String(value)}
function cleanPhaseName(name){return String(name||"Etapa").replace(/\s*\([^)]*\b(?:\d+(?:[.,]\d+)?(?:\s*[-–a]\s*\d+(?:[.,]\d+)?)?\s*)?rpm\b[^)]*\)/gi,"").replace(/\s{2,}/g," ").trim()}
function spokenPhaseName(name){return cleanPhaseName(name).replace(/\s*[·-]\s*\d+\s*\/\s*\d+\s*$/u,"").trim()}
function normalizeSpeechText(value){return String(value||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9áéíóúüñ]+/gi," ").replace(/\s+/g," ").trim()}
function uniqueSpeechParts(parts){const result=[],seen=[];for(const raw of parts){for(const piece of String(raw||"").split(/[.;]+/)){const text=piece.trim();if(!text)continue;const key=normalizeSpeechText(text);if(!key)continue;if(seen.some(previous=>previous===key||(key.length>=12&&previous.includes(key))))continue;seen.push(key);result.push(text)}}return result}
function muteMusicForVoice(){if(state.musicAudio){state.musicAudio.dataset.preVoiceVolume=String(state.musicAudio.volume);state.musicAudio.volume=0}}
function restoreMusicAfterVoice(token){if(token!==state.speechToken)return;const audio=state.musicAudio,s=state.session;if(audio&&s?.musicEnabled)audio.volume=s.musicVolume}
function stopSpeechWatchdog(){clearInterval(state.speechWatchdog);state.speechWatchdog=null}
function keepSpeechActive(){const synth=window.speechSynthesis;if(!state.speechUtterance||!synth)return;try{if(synth.paused)synth.resume()}catch{}}
function startSpeechWatchdog(token){stopSpeechWatchdog();state.speechWatchdog=setInterval(()=>{if(token!==state.speechToken||!state.speechUtterance)return stopSpeechWatchdog();keepSpeechActive()},700)}
function stopSpeech(){window.speechSynthesis?.cancel();state.speechToken++;state.speechUtterance=null;stopSpeechWatchdog();restoreMusicAfterVoice(state.speechToken)}
function speakPhase(p){const s=state.session;if(!s?.voiceEnabled||s.voiceVolume<=0||!("speechSynthesis" in window)||p.voice===false)return;const token=++state.speechToken;window.speechSynthesis.cancel();const parts=[spokenPhaseName(p.name)];if(p.repetitionCount)parts.push(`${spokenNumber(p.repetition)} de ${spokenNumber(p.repetitionCount)}`);parts.push(p.duration);if(p.zone){const z=String(p.zone).match(/Z([1-5])/i)?.[1];parts.push(z?`Zona ${spokenNumber(z)}`:`Zona ${p.zone}`)}parts.push(p.cadence&&!/^cadencia libre$/i.test(String(p.cadence).trim())?String(p.cadence):"Cadencia libre");const target=p.hr&&p.hr!=="Según zona"?p.hr:hrTarget(p.zone||state.day.zone,s.maxHr);if(target!=="—")parts.push(`Pulsaciones ${target}`);if(p.technique)parts.push(p.technique);const text=uniqueSpeechParts(parts).join(". "),u=new SpeechSynthesisUtterance(text);state.speechUtterance=u;u.lang="es-AR";u.volume=s.voiceVolume;u.rate=1.08;u.onstart=()=>{muteMusicForVoice();startSpeechWatchdog(token)};u.onpause=keepSpeechActive;u.onend=()=>{if(token!==state.speechToken)return;state.speechUtterance=null;stopSpeechWatchdog();restoreMusicAfterVoice(token)};u.onerror=()=>{if(token!==state.speechToken)return;state.speechUtterance=null;stopSpeechWatchdog();restoreMusicAfterVoice(token)};window.speechSynthesis.speak(u);keepSpeechActive()}
function replayCurrentPhaseVoice(event){if(event?.target?.closest("button"))return;const s=state.session,p=s?.phases?.[s.phaseIndex];if(p)speakPhase(p)}
function populateTrackSelect(el,selected=""){el.innerHTML='<option value="">Automático</option>'+state.musicLibrary.map(t=>`<option value="${escapeHtml(t.name)}">${escapeHtml(t.name)}</option>`).join("");el.value=[...el.options].some(o=>o.value===selected)?selected:""}
function populatePhaseMusicSelect(selected="auto",preferences=[]){const mode=$("#editPhaseMusic");mode.value=selected==="off"?"off":"auto";[1,2,3].forEach((n,i)=>populateTrackSelect($("#editPhaseMusic"+n),preferences[i]||((selected!=="auto"&&selected!=="off"&&i===0)?selected:"")))}
function togglePreferredMusicFields(){$("#preferredMusicFields").hidden=$("#editPhaseMusic").value==="off"}
function loadMusicLibrary(e){clearMusicObjectUrls();state.musicLibrary=[...(e.target.files||[])].map(file=>({file,name:file.name,bpm:extractBpm(file.name),url:URL.createObjectURL(file),path:file.webkitRelativePath||file.name,energy:inferTrackEnergy(file.name)}));state.musicDirectoryHandle=null;state.musicIndexedAt=new Date();resetMusicAssignments();updateMusicLibraryStatus();populatePhaseMusicSelect("auto",[])}
function clearMusicObjectUrls(){for(const track of state.musicLibrary){if(track.url)try{URL.revokeObjectURL(track.url)}catch{}}}
function resetMusicAssignments(){state.phaseTrackAssignments.clear();state.phaseTrackQueues.clear();state.musicUsedByPhase.clear()}
function inferTrackEnergy(text){const s=String(text).toLowerCase();if(/recup|relax|suave|ambient|calma|chill/.test(s))return"low";if(/rock|metal|power|intenso|hard|vo2|sprint/.test(s))return"high";return"medium"}
function openMusicHandleDb(){return new Promise((resolve,reject)=>{const req=indexedDB.open("rpc-music-library",1);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains("handles"))req.result.createObjectStore("handles")};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function saveMusicDirectoryHandle(handle){try{const db=await openMusicHandleDb();await new Promise((resolve,reject)=>{const tx=db.transaction("handles","readwrite");tx.objectStore("handles").put(handle,"directory");tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}catch(e){console.warn("No se pudo guardar la carpeta musical",e)}}
async function loadMusicDirectoryHandle(){try{const db=await openMusicHandleDb();return await new Promise((resolve,reject)=>{const tx=db.transaction("handles","readonly"),req=tx.objectStore("handles").get("directory");req.onsuccess=()=>resolve(req.result||null);req.onerror=()=>reject(req.error)})}catch{return null}}
async function musicHandlePermission(handle,request=false){if(!handle)return false;try{if(await handle.queryPermission({mode:"read"})==="granted")return true;if(request&&await handle.requestPermission({mode:"read"})==="granted")return true}catch{}return false}
async function chooseMusicFolder(){if(!window.showDirectoryPicker){$("#musicLibraryStatus").textContent="Este navegador no admite carpetas persistentes. Use la selección manual de canciones.";return}try{const handle=await window.showDirectoryPicker({mode:"read"});state.musicDirectoryHandle=handle;await saveMusicDirectoryHandle(handle);await indexMusicDirectory(handle,true)}catch(e){if(e?.name!=="AbortError")$("#musicLibraryStatus").textContent="No se pudo acceder a la carpeta musical."}}
async function walkMusicDirectory(handle,prefix=""){const tracks=[];for await(const [name,entry] of handle.entries()){const path=prefix?`${prefix}/${name}`:name;if(entry.kind==="directory")tracks.push(...await walkMusicDirectory(entry,path));else if(entry.kind==="file"&&/\.(mp3|m4a|aac|ogg|oga|wav|flac|opus)$/i.test(name)){const file=await entry.getFile();tracks.push({file,handle:entry,name:file.name,bpm:extractBpm(file.name),url:URL.createObjectURL(file),path,energy:inferTrackEnergy(path)})}}return tracks}
async function indexMusicDirectory(handle,requestPermission=false){if(!await musicHandlePermission(handle,requestPermission)){state.musicDirectoryHandle=handle;updateMusicLibraryStatus("permission");return false}try{clearMusicObjectUrls();state.musicLibrary=await walkMusicDirectory(handle);state.musicDirectoryHandle=handle;state.musicIndexedAt=new Date();localStorage.setItem("rpc.musicIndexMeta",JSON.stringify({folder:handle.name,count:state.musicLibrary.length,at:state.musicIndexedAt.toISOString()}));resetMusicAssignments();updateMusicLibraryStatus("ok");populatePhaseMusicSelect("auto",[]);return true}catch(e){console.error(e);updateMusicLibraryStatus("error");return false}}
async function restoreMusicFolder(requestPermission=false){let handle=state.musicDirectoryHandle||await loadMusicDirectoryHandle();if(!handle){updateMusicLibraryStatus();return false}state.musicDirectoryHandle=handle;return indexMusicDirectory(handle,requestPermission)}
async function ensureMusicLibraryReady(requestPermission=false){if(state.musicLibrary.length)return true;if(state.musicRestorePromise){try{await state.musicRestorePromise}catch{}state.musicRestorePromise=null;if(state.musicLibrary.length)return true}state.musicRestorePromise=restoreMusicFolder(requestPermission).catch(()=>false);const ready=await state.musicRestorePromise;state.musicRestorePromise=null;return Boolean(ready&&state.musicLibrary.length)}
function extractBpm(name){const explicit=String(name).match(/(?:^|[^0-9])(\d{2,3})\s*(?:bpm)?(?:[^0-9]|$)/i);const n=Number(explicit?.[1]||0);return n>=50&&n<=200?n:0}
function updateMusicLibraryStatus(mode=""){const status=$("#musicLibraryStatus"),count=$("#musicTrackCount"),folder=$("#musicFolderName"),indexed=$("#musicIndexedAt"),badge=$("#musicPermissionBadge");let meta=null;try{meta=JSON.parse(localStorage.getItem("rpc.musicIndexMeta")||"null")}catch{}const folderName=state.musicDirectoryHandle?.name||meta?.folder||"Sin carpeta seleccionada";const total=state.musicLibrary.length||meta?.count||0;const at=state.musicIndexedAt||(meta?.at?new Date(meta.at):null);if(folder)folder.textContent=folderName;if(count)count.textContent=String(total);if(indexed)indexed.textContent=at?at.toLocaleString():"—";if(badge){badge.className="";if(mode==="ok"||state.musicLibrary.length){badge.textContent="Disponible";badge.classList.add("ok")}else if(mode==="permission"){badge.textContent="Autorizar";badge.classList.add("warn")}else badge.textContent="Sin acceso"}if(status){if(mode==="permission")status.textContent="La carpeta está recordada, pero Android requiere volver a autorizar el acceso.";else if(mode==="error")status.textContent="No se pudo indexar la carpeta seleccionada.";else if(state.musicLibrary.length)status.textContent=`${state.musicLibrary.length} canciones disponibles para todos los entrenamientos.`;else status.textContent="Seleccione una carpeta de memoria interna o tarjeta SD, o use la selección manual."}}
function musicTarget(p){const z=(p.zone||"").match(/Z[1-5]/)?.[0],cad=Number(p.cadenceRpm)||Number(String(p.cadence||"").match(/\d{2,3}/)?.[0])||0;return cad||({Z1:72,Z2:88,Z3:106,Z4:122,Z5:138}[z]||90)}
function dayMusicSeed(){const text=`${state.week?.number||0}-${state.dayName||""}`;return [...text].reduce((a,c)=>(a*31+c.charCodeAt(0))>>>0,7)}
function rankedPhaseTracks(p){const target=musicTarget(p),seed=dayMusicSeed(),tracks=[...state.musicLibrary],zone=String(p.zone||"").toUpperCase(),low=/recuperaci|calma|enfri/i.test(p.name||"")||zone==="Z1",high=["Z4","Z5"].includes(zone)||target>=95;const score=t=>Math.abs((t.bpm||target)-target)+(low&&t.energy!=="low"?20:0)+(high&&t.energy!=="high"?14:0);return tracks.sort((a,b)=>{const da=score(a),db=score(b);if(da!==db)return da-db;const ai=state.musicLibrary.indexOf(a),bi=state.musicLibrary.indexOf(b);return ((ai+seed+(p.index||0)*3)%Math.max(1,tracks.length))-((bi+seed+(p.index||0)*3)%Math.max(1,tracks.length))})}
function musicKey(p){return p.musicGroup||`phase-${p.index??0}`}
function rememberMusicOrder(){const order=[...state.phaseTrackAssignments.values()];localStorage.setItem(`rpc.musicOrder.${state.week?.number||0}.${state.dayName}`,JSON.stringify(order))}
function phaseQueue(p){const key=musicKey(p);if(state.phaseTrackQueues.has(key))return state.phaseTrackQueues.get(key);const preferred=(p.musicPreferences||[]).map(name=>state.musicLibrary.find(t=>t.name===name)).filter(Boolean),ranked=rankedPhaseTracks(p).filter(t=>!preferred.some(x=>x.name===t.name));const queue=[...preferred,...ranked];state.phaseTrackQueues.set(key,queue);return queue}
function choosePhaseTrack(p,advance=false){if(!state.musicLibrary.length||p.music==="off")return null;const key=musicKey(p),queue=phaseQueue(p);if(!queue.length)return null;const currentName=state.phaseTrackAssignments.get(key);if(currentName&&!advance)return state.musicLibrary.find(t=>t.name===currentName)||queue[0];const used=state.musicUsedByPhase.get(key)||new Set(),currentIndex=Math.max(-1,queue.findIndex(t=>t.name===currentName));let track=null;for(let step=1;step<=queue.length;step++){const candidate=queue[(currentIndex+step)%queue.length];if(!used.has(candidate.name)){track=candidate;break}}if(!track){used.clear();track=queue[(currentIndex+1)%queue.length]}used.add(track.name);state.musicUsedByPhase.set(key,used);state.phaseTrackAssignments.set(key,track.name);rememberMusicOrder();return track}
function saveCurrentMusicPosition(){const audio=state.musicAudio;if(audio&&state.currentMusicKey&&Number.isFinite(audio.currentTime))state.musicPositions.set(state.currentMusicKey,audio.currentTime)}
function updateMusicMediaSession(track){if(!("mediaSession" in navigator))return;try{navigator.mediaSession.metadata=new MediaMetadata({title:track?.name||"Música de entrenamiento",artist:"Río Pinto Coach",album:"Entrenamiento MTB"})}catch{}}
function ensureMusicPlayer(){if(state.musicAudio)return state.musicAudio;const audio=new Audio();audio.preload="auto";audio.autoplay=true;audio.playsInline=true;audio.addEventListener("loadedmetadata",()=>{const saved=Number(state.musicPendingResume)||0;if(saved>0&&saved<audio.duration)try{audio.currentTime=saved}catch{}state.musicPendingResume=0});audio.addEventListener("canplay",()=>{const s=state.session;if(s?.musicEnabled&&!s.musicPausedByUser&&audio.paused)playMusicReliably()});audio.addEventListener("timeupdate",()=>{if(state.currentMusicKey&&Number.isFinite(audio.currentTime))state.musicPositions.set(state.currentMusicKey,audio.currentTime)});audio.addEventListener("ended",()=>{const s=state.session,p=state.musicCurrentPhase;if(!s?.musicEnabled||s.musicPausedByUser||!p)return;if(p.musicResume){audio.currentTime=0;playMusicReliably()}else playNextPhaseTrack(true)});audio.addEventListener("error",()=>{const s=state.session;if(s?.musicEnabled&&!s.musicPausedByUser)playNextPhaseTrack(true)});audio.addEventListener("play",()=>{state.musicStartedAt=Date.now();if("mediaSession" in navigator)try{navigator.mediaSession.playbackState="playing"}catch{}updateMusicButton()});audio.addEventListener("pause",()=>{if("mediaSession" in navigator)try{navigator.mediaSession.playbackState="paused"}catch{}updateMusicButton()});if("mediaSession" in navigator){try{navigator.mediaSession.setActionHandler("play",()=>{const s=state.session;if(!s?.musicEnabled)return;s.musicPausedByUser=false;playMusicReliably();updateMusicButton()});navigator.mediaSession.setActionHandler("pause",()=>{const s=state.session;if(s)s.musicPausedByUser=true;audio.pause();updateMusicButton()});navigator.mediaSession.setActionHandler("nexttrack",()=>playNextPhaseTrack(false))}catch{}}state.musicAudio=audio;return audio}
function startMusicWatchdog(){if(state.musicWatchdog)return;state.musicWatchdog=setInterval(()=>{const s=state.session,a=state.musicAudio,p=state.musicCurrentPhase;if(!s||s.finished||!s.musicEnabled||s.musicPausedByUser||!a||!p)return;if(a.ended)return p.musicResume?(a.currentTime=0,playMusicReliably()):playNextPhaseTrack(true);if(a.paused)playMusicReliably();else if(a.readyState<2&&Date.now()-state.musicStartedAt>15000)playNextPhaseTrack(true)},4000)}
function stopMusicWatchdog(){clearInterval(state.musicWatchdog);state.musicWatchdog=null;clearTimeout(state.musicRetryTimer);state.musicRetryTimer=null}
function createMusicAudio(track,p,resume=true){const s=state.session,key=musicKey(p),audio=ensureMusicPlayer();state.musicCurrentPhase=p;state.musicCurrentTrack=track;updateMusicMediaSession(track);state.currentMusicKey=key;state.musicPendingResume=resume?(state.musicPositions.get(key)||0):0;audio.pause();audio.loop=Boolean(p.musicResume);audio.dataset.track=track.name;audio.volume=s.musicVolume;audio.src=track.url;audio.load();state.musicStartedAt=Date.now();startMusicWatchdog();if(!s.musicPausedByUser)playMusicReliably();else updateMusicButton()}
function switchPhaseMusic(p){const s=state.session;if(!s?.musicEnabled){stopPhaseMusic();return}const track=choosePhaseTrack(p);if(!track){stopPhaseMusic();return}const key=musicKey(p),audio=ensureMusicPlayer();if(audio.dataset.track===track.name&&state.currentMusicKey===key){state.musicCurrentPhase=p;audio.volume=s.musicVolume;if(s.musicPausedByUser&&!audio.paused)audio.pause();else if(!s.musicPausedByUser&&audio.paused)playMusicReliably();updateMusicButton();return}saveCurrentMusicPosition();createMusicAudio(track,p,true)}
function playNextPhaseTrack(fromEnded=false){const s=state.session,p=s?.phases?.[s.phaseIndex];if(!s?.musicEnabled||!p||!state.musicLibrary.length)return;const key=musicKey(p);if(!fromEnded)state.musicPositions.set(key,0);const track=choosePhaseTrack(p,true);if(!track)return;saveCurrentMusicPosition();createMusicAudio(track,p,false)}
function handlePhaseMusicTap(){const now=performance.now();if(now-state.lastMusicTap<340){clearTimeout(state.musicTapTimer);state.musicTapTimer=null;state.lastMusicTap=0;playNextPhaseTrack(false);return}state.lastMusicTap=now;clearTimeout(state.musicTapTimer);state.musicTapTimer=setTimeout(()=>{state.musicTapTimer=null;state.lastMusicTap=0;const s=state.session;if(!s?.musicEnabled)return;s.musicPausedByUser=!s.musicPausedByUser;const audio=ensureMusicPlayer();if(s.musicPausedByUser)audio.pause();else if(audio.src)playMusicReliably();else switchPhaseMusic(s.phases[s.phaseIndex]);updateMusicButton()},300)}
function updateMusicButton(){const b=$("#phaseMusicButton"),s=state.session;if(!b)return;const unavailable=!s?.musicEnabled||!state.musicLibrary.length,playing=!unavailable&&!s.musicPausedByUser&&state.musicAudio&&!state.musicAudio.paused;b.disabled=unavailable;b.textContent=playing?"Ⅱ":"▶";b.classList.toggle("is-user-paused",Boolean(s?.musicPausedByUser));b.setAttribute("aria-label",playing?"Pausar música para todo el entrenamiento; doble toque para siguiente tema":"Reanudar música para todo el entrenamiento; doble toque para siguiente tema")}
function stopPhaseMusic(clearSource=true){const audio=state.musicAudio;if(audio){saveCurrentMusicPosition();audio.pause();if(clearSource){audio.removeAttribute("src");audio.load()}}state.currentMusicKey=null;state.musicCurrentPhase=null;state.musicCurrentTrack=null;if(clearSource)stopMusicWatchdog();updateMusicButton()}
function clearGpsWatch(){if(state.gpsWatch!==null&&navigator.geolocation)navigator.geolocation.clearWatch(state.gpsWatch);state.gpsWatch=null}
function startGps(preserveLastPosition=false){const s=state.session;if(!s)return;if(!navigator.geolocation){$("#gpsStatus").textContent="GPS: no disponible";return}clearGpsWatch();if(!preserveLastPosition){s.lastPosition=null;s.gpsAnchor=null;s.gpsMotionStreak=0}else s.gpsResumePending=true;s.lastGpsReceived=Date.now();$("#gpsStatus").textContent=preserveLastPosition?"GPS: recuperando":"GPS: buscando";state.gpsWatch=navigator.geolocation.watchPosition(onGps,onGpsError,{enableHighAccuracy:true,maximumAge:0,timeout:20000});startGpsMonitor()}
function startGpsMonitor(){clearInterval(state.gpsMonitor);state.gpsMonitor=setInterval(()=>{const s=state.session;if(!s||s.finished||!s.gps)return;if(Date.now()-s.lastGpsReceived>25000)startGps(true)},10000)}
function stopGps(){clearGpsWatch();clearInterval(state.gpsMonitor);state.gpsMonitor=null}
function median(values){const ordered=[...values].sort((a,b)=>a-b),mid=Math.floor(ordered.length/2);return ordered.length%2?ordered[mid]:(ordered[mid-1]+ordered[mid])/2}
function updatePositiveElevation(coords){const s=state.session,alt=Number(coords.altitude),altAccuracy=Number(coords.altitudeAccuracy);if(!Number.isFinite(alt)||(Number.isFinite(altAccuracy)&&altAccuracy>30))return;s.altitudeWindow.push(alt);if(s.altitudeWindow.length>5)s.altitudeWindow.shift();const filtered=median(s.altitudeWindow),threshold=Math.max(2.5,Math.min(6,(Number.isFinite(altAccuracy)?altAccuracy:12)*.18));if(!Number.isFinite(s.elevationAnchor)){s.elevationAnchor=filtered;return}const delta=filtered-s.elevationAnchor;if(delta>=threshold){s.elevation+=delta;s.elevationAnchor=filtered}else if(delta<=-threshold)s.elevationAnchor=filtered}
function onGps(pos){const s=state.session;if(!s)return;const c=pos.coords,now=pos.timestamp||Date.now(),wallNow=Date.now(),accuracy=Number(c.accuracy)||999,recovering=Boolean(s.gpsResumePending),current={lat:c.latitude,lon:c.longitude,t:now,accuracy};s.lastGpsReceived=wallNow;$("#gpsStatus").textContent=`GPS: ±${Math.round(accuracy)} m`;if(s.paused){s.lastPosition=current;s.gpsAnchor=current;s.gpsMotionStreak=0;s.gpsMoving=false;s.gpsLastMotionAt=0;s.gpsSpeedUpdatedAt=0;s.speed=0;s.gpsResumePending=false;s.gpsHiddenAt=0;return}if(accuracy>45){if(!s.gpsMoving||wallNow-s.gpsSpeedUpdatedAt>5000)s.speed=0;return}if(!s.gpsAnchor){s.gpsAnchor=current;s.lastPosition=current;s.speed=0;s.gpsMotionStreak=0;s.gpsMoving=false;s.gpsResumePending=false;s.gpsHiddenAt=0;return}const anchor=s.gpsAnchor,dt=(now-anchor.t)/1000,dist=haversine(anchor.lat,anchor.lon,c.latitude,c.longitude),uncertainty=Math.max(5,Math.min(20,(accuracy+(anchor.accuracy||accuracy))*.35)),sensorSpeed=Number.isFinite(c.speed)&&c.speed>=0?c.speed*3.6:null,derivedSpeed=dt>0?dist/dt*3.6:0,maxGap=recovering?21600:120,plausible=dt>0&&dt<maxGap&&derivedSpeed<=80&&dist<Math.max(recovering?1000:180,dt*22.2),speedEvidence=(sensorSpeed!=null&&sensorSpeed>=1.5)||derivedSpeed>=2.2,candidate=plausible&&dist>uncertainty&&derivedSpeed>=1.5&&speedEvidence;if(candidate)s.gpsMotionStreak=Math.min(2,s.gpsMotionStreak+1);else if(!s.gpsMoving)s.gpsMotionStreak=0;const confirmed=candidate&&(recovering||s.gpsMoving||s.gpsMotionStreak>=2);if(confirmed){const measured=sensorSpeed!=null&&sensorSpeed>=1.5?sensorSpeed:derivedSpeed;s.distance+=dist/1000;s.speed=s.speed>0?s.speed*.55+measured*.45:measured;s.gpsAnchor=current;s.gpsMotionStreak=2;s.gpsMoving=true;s.gpsLastMotionAt=now;s.gpsSpeedUpdatedAt=wallNow;updatePositiveElevation(c)}else if(s.gpsMoving){if(now-s.gpsLastMotionAt>5000){s.gpsMoving=false;s.gpsMotionStreak=0;s.speed=0;s.gpsAnchor=current}}else{s.speed=0;if(dt>120&&!recovering)s.gpsAnchor=current}s.lastPosition=current;s.gpsResumePending=false;s.gpsHiddenAt=0}
function onGpsError(err){$("#gpsStatus").textContent=err.code===1?"GPS: permiso denegado":err.code===3?"GPS: reintentando":"GPS: sin señal";if(err.code===3&&state.session?.gps)setTimeout(()=>{if(state.session)startGps(true)},1500)}
function haversine(a,b,c,d){const R=6371000,x=(c-a)*Math.PI/180,y=(d-b)*Math.PI/180,q=Math.sin(x/2)**2+Math.cos(a*Math.PI/180)*Math.cos(c*Math.PI/180)*Math.sin(y/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
function trainingRecords(){try{return JSON.parse(localStorage.getItem("rpc.trainingRecords")||"[]")}catch{return []}}
function totalPlannedTrainings(){return state.data?.weeks?.reduce((sum,w)=>sum+Object.keys(w.days||{}).length,0)||0}
function saveTrainingRecord(){const s=state.session;if(!s)return;const avgSpeed=averageSessionSpeed(s),avgHr=s.sampleSeconds&&s.hrWeighted?s.hrWeighted/s.sampleSeconds:0,completed=s.phaseResults.map((r,i)=>({...r,index:i,name:cleanPhaseName(s.phases[i].name),planned:s.phases[i].durationSeconds})).filter(r=>r.status==="completed"),completedSeconds=completed.reduce((sum,r)=>sum+r.planned,0),record={id:`${Date.now()}-${state.week.number}-${state.dayName}`,date:new Date().toISOString(),week:state.week.number,day:state.dayName,title:state.day.title,plannedDuration:s.plannedTotal,actualDuration:s.averageElapsed,phaseDuration:s.totalElapsed,completedDuration:completedSeconds,completion:s.plannedTotal?Math.min(100,Math.round(completedSeconds/s.plannedTotal*100)):0,completedPhases:completed,skippedPhases:s.phaseResults.filter(r=>r.status==="skipped").length,objectives:{zone:state.day.zone||"—",cadence:state.day.cadence||"Cadencia libre",distance:state.day.distance||"—",phases:s.phases.map(p=>({name:cleanPhaseName(p.name),duration:p.duration,zone:p.zone,cadence:p.cadence,hr:p.hr}))},actual:{distance:Number(s.distance.toFixed(2)),avgSpeed:Number(avgSpeed.toFixed(1)),elevation:Math.round(s.elevation),avgHr:Math.round(avgHr)}},records=trainingRecords();records.push(record);localStorage.setItem("rpc.trainingRecords",JSON.stringify(records));renderProgressCard()}
function progressData(){const records=trainingRecords(),total=totalPlannedTrainings(),unique=new Set(records.filter(r=>r.completion>=100).map(r=>`${r.week}-${r.day}`)).size,percent=total?Math.min(100,Math.round(unique/total*100)):0;return {records,total,unique,percent}}
function renderProgressCard(){if(!state.data||!$("#progressCard"))return;const d=progressData();$("#progressPercent").textContent=`${d.percent}%`;$("#progressSummary").textContent=`${d.unique} de ${d.total} entrenamientos`;$("#progressWeeks").textContent=`Plan de ${state.data.weeks.length} semanas`;$("#progressDonut").style.setProperty("--progress",d.percent)}
function deleteTrainingRecord(id){const records=trainingRecords(),record=records.find(r=>r.id===id);if(!record)return;const date=new Date(record.date).toLocaleDateString("es-AR"),label=`Semana ${record.week} · ${record.day} · ${date}`;if(!confirm(`¿Desea eliminar el registro de entrenamiento de ${label}?`))return;localStorage.setItem("rpc.trainingRecords",JSON.stringify(records.filter(r=>r.id!==id)));renderProgressCard();openHistory()}
function openHistory(){const d=progressData(),list=$("#historyList"),dialog=$("#historyDialog");$("#historySummary").innerHTML=`<strong>${d.percent}% completado</strong><span>${d.unique} de ${d.total} entrenamientos del plan</span>`;list.innerHTML=d.records.length?[...d.records].reverse().map(r=>`<details class="history-record"><summary><span>Semana ${r.week} · ${escapeHtml(r.day)}</span><span class="history-record-date"><strong>${new Date(r.date).toLocaleDateString("es-AR")}</strong><button class="history-delete-button" type="button" data-record-id="${escapeHtml(r.id)}" aria-label="Eliminar registro del ${new Date(r.date).toLocaleDateString("es-AR")}" title="Eliminar registro">×</button></span></summary><div class="history-columns"><section><h3>OBJETIVOS</h3><p>Duración: ${formatClock(r.plannedDuration,true)}</p><p>Zona: ${escapeHtml(r.objectives.zone)}</p><p>Cadencia: ${escapeHtml(r.objectives.cadence)}</p><p>Distancia: ${escapeHtml(r.objectives.distance)}</p></section><section><h3>REGISTRADO</h3><p>Duración: ${formatClock(r.actualDuration,true)}</p><p>Cumplimiento: ${r.completion}%</p><p>Etapas completadas: ${r.completedPhases?.length||0}/${r.objectives.phases.length}</p><p>Etapas omitidas: ${r.skippedPhases||0}</p><p>Distancia: ${r.actual.distance.toFixed(2)} km</p><p>Velocidad media: ${r.actual.avgSpeed.toFixed(1)} km/h</p><p>Desnivel: +${r.actual.elevation} m</p><p>FC media: ${r.actual.avgHr||"—"} ppm</p></section></div></details>`).join(""):'<p class="empty-history">Todavía no hay entrenamientos guardados.</p>';list.querySelectorAll(".history-delete-button").forEach(button=>button.addEventListener("click",event=>{event.preventDefault();event.stopPropagation();deleteTrainingRecord(button.dataset.recordId)}));if(!dialog.open)dialog.showModal()}
function setupInstallPrompt(){const hint=$("#installHint");addEventListener("beforeinstallprompt",event=>{event.preventDefault();state.deferredInstall=event;hint.hidden=false;hint.textContent="Tocá aquí para instalar la aplicación.";hint.setAttribute("role","button");hint.tabIndex=0});const install=async()=>{if(!state.deferredInstall)return;state.deferredInstall.prompt();await state.deferredInstall.userChoice;state.deferredInstall=null;hint.hidden=true};hint.addEventListener("click",install);hint.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" ")install()});addEventListener("appinstalled",()=>{state.deferredInstall=null;hint.hidden=true})}
async function requestWakeLock(){try{if(!("wakeLock" in navigator)||document.visibilityState!=="visible")return;if(state.wakeLock&&!state.wakeLock.released)return;state.wakeLock=await navigator.wakeLock.request("screen");state.wakeLock.addEventListener("release",()=>{state.wakeLock=null;if(document.visibilityState==="visible"&&state.session&&!state.session.finished)setTimeout(requestWakeLock,500)},{once:true})}catch{}}
function releaseWakeLock(){try{state.wakeLock?.release()}catch{}state.wakeLock=null}
document.addEventListener("visibilitychange",()=>{const s=state.session;keepSpeechActive();if(!s||s.finished)return;if(document.visibilityState==="hidden"){s.gpsHiddenAt=Date.now();s.gpsResumePending=Boolean(s.gps);keepSpeechActive();return}tick();requestWakeLock();keepSpeechActive();if(s.gps&&(s.gpsHiddenAt||Date.now()-s.lastGpsReceived>12000))startGps(true);const p=s.phases?.[s.phaseIndex];if(s.voiceEnabled&&p&&s.transition&&!state.speechUtterance)speakPhase(p);if(s.musicEnabled&&!s.musicPausedByUser&&state.musicAudio?.paused)playMusicReliably()});
function escapeHtml(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}addEventListener("popstate",()=>{if(!location.hash&&state.session)$("#finishDialog").showModal();else if(!location.hash)closePrepare()});init().catch(err=>{document.body.innerHTML=`<main class="app"><section class="card"><h2>Error</h2><p>${escapeHtml(err.message)}</p></section></main>`});

